-- 0095_loi_template_seed.sql
-- Seed a professional Letter of Intent contract template for the e-sign v2 engine.
-- This template is used when sending an LOI for electronic signature.

INSERT INTO contract_templates (name, description, category, content, merge_fields, is_active, status, version, source_format)
VALUES (
  'Letter of Intent (LOI)',
  'Non-binding letter of intent for real estate wholesale transactions. Used when sending an LOI for electronic signature.',
  'loi',
  '<div style="text-align: center; margin-bottom: 30px;">
  <div style="font-size: 11px; letter-spacing: 3px; color: #8a6d2b; margin-bottom: 8px;">OCEAN LUXE</div>
  <h1 style="font-size: 24px; margin: 0; letter-spacing: 1px;">LETTER OF INTENT</h1>
  <div style="font-size: 11px; color: #666; margin-top: 8px;">Non-Binding Offer to Purchase Real Property</div>
</div>

<p><strong>Date:</strong> {{date}}</p>

<table style="width: 100%; border-collapse: collapse; margin-bottom: 24px; font-size: 13px;">
  <tr>
    <td style="padding: 10px; border: 1px solid #ccc; background: #f9f9f9; width: 30%;"><strong>Buyer</strong></td>
    <td style="padding: 10px; border: 1px solid #ccc;">{{buyerName}}</td>
  </tr>
  <tr>
    <td style="padding: 10px; border: 1px solid #ccc; background: #f9f9f9;"><strong>Seller</strong></td>
    <td style="padding: 10px; border: 1px solid #ccc;">{{sellerName}}</td>
  </tr>
  <tr>
    <td style="padding: 10px; border: 1px solid #ccc; background: #f9f9f9;"><strong>Property</strong></td>
    <td style="padding: 10px; border: 1px solid #ccc;">{{propertyAddress}}</td>
  </tr>
</table>

<h2>Proposed Terms</h2>
<table style="width: 100%; border-collapse: collapse; margin-bottom: 24px; font-size: 13px;">
  <tr>
    <td style="padding: 10px; border: 1px solid #ccc; background: #f9f9f9; width: 40%;"><strong>Purchase Price</strong></td>
    <td style="padding: 10px; border: 1px solid #ccc; font-size: 16px; font-weight: bold;">{{offerAmount}}</td>
  </tr>
  <tr>
    <td style="padding: 10px; border: 1px solid #ccc; background: #f9f9f9;"><strong>Earnest Money Deposit</strong></td>
    <td style="padding: 10px; border: 1px solid #ccc;">{{earnestMoney}}</td>
  </tr>
  <tr>
    <td style="padding: 10px; border: 1px solid #ccc; background: #f9f9f9;"><strong>Target Closing Date</strong></td>
    <td style="padding: 10px; border: 1px solid #ccc;">{{closingDate}}</td>
  </tr>
  <tr>
    <td style="padding: 10px; border: 1px solid #ccc; background: #f9f9f9;"><strong>Offer Expires</strong></td>
    <td style="padding: 10px; border: 1px solid #ccc;">{{expiresAt}}</td>
  </tr>
</table>

<h2>Contingencies</h2>
{{contingencies}}

<h2>Special Terms</h2>
<p>{{specialTerms}}</p>

<h2>Non-Binding Nature</h2>
<p>This Letter of Intent is for discussion purposes only and does not create a binding obligation on either party, except as may be set forth in a mutually executed definitive purchase agreement. Either party may terminate discussions at any time.</p>

<div style="margin-top: 60px;">
  <p><strong>AGREED AND ACCEPTED:</strong></p>
  <table style="width: 100%; font-size: 13px; margin-top: 20px;">
    <tr>
      <td style="width: 50%; padding-right: 20px;">
        <div style="border-bottom: 1px solid #111; height: 50px; margin-bottom: 6px;"></div>
        <div style="font-size: 11px; color: #555;">Buyer: {{buyerName}}</div>
        <div style="margin-top: 12px; border-bottom: 1px solid #111; height: 30px; margin-bottom: 6px;"></div>
        <div style="font-size: 11px; color: #555;">Date</div>
      </td>
      <td style="width: 50%; padding-left: 20px;">
        <div style="border-bottom: 1px solid #111; height: 50px; margin-bottom: 6px;"></div>
        <div style="font-size: 11px; color: #555;">Seller: {{sellerName}}</div>
        <div style="margin-top: 12px; border-bottom: 1px solid #111; height: 30px; margin-bottom: 6px;"></div>
        <div style="font-size: 11px; color: #555;">Date</div>
      </td>
    </tr>
  </table>
</div>

<div style="margin-top: 40px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 10px; color: #888; text-align: center;">
  Generated by Ocean Luxe CRM &nbsp;·&nbsp; This document is a non-binding letter of intent and does not constitute legal advice.
</div>',
  ARRAY['buyerName', 'sellerName', 'propertyAddress', 'offerAmount', 'earnestMoney', 'closingDate', 'expiresAt', 'contingencies', 'specialTerms', 'date'],
  true,
  'active',
  1,
  'html'
)
ON CONFLICT DO NOTHING;
